name: Build macOS App (Alternative)

on:
  push:
    branches: [ test01, main ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (macOS only)
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build the app using Tauri Action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Ittehad Iron Store v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: --target universal-apple-darwin

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
          
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app
