name: Build macOS App

on:
  push:
    branches: [ test01, main ]
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request:
    branches: [ test01, main ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin,x86_64-apple-darwin
    
    - name: Build the app
      run: cargo tauri build --target universal-apple-darwin
    
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app
